GET http://localhost:3000/games
###
POST http://localhost:3000/games HTTP/1.1 
content-type: application/json

{
  "title": "This is a test on local",
  "hoursPlayed": 5
}
###
GET http://localhost:3000/games/67311ac060e0e2fd2f1b2
###
PUT http://localhost:3000/games/67311ac060e0e2fd2f1b2240 HTTP/1.1 
content-type: application/json

{
  "title": "success",
  "hoursPlayed": 6
}
###
GET https://game-suggester.onrender.com/games
###
POST https://game-suggester.onrender.com/games
Content-Type: application/json

{
  "title": "This is a test"
}
###